from selenium.webdriver.common.by import By

class DoskaLocators:
    EMAIL = By.NAME, "email"
    PASSWORD = By.NAME, "password"
    LOGIN_BUTTON = By.XPATH, ".//button[text()='Войти']"
    LOGOUT_BUTTON = By.XPATH, ".//button[text()='Выйти']"
    LOGIN_FORM = By.XPATH, ".//form[@class='popUp_shell__LuyqR']"
    SUBMIT_PASSWORD = By.NAME, "submitPassword"
    BUTTON_CREATE_ACC = By.XPATH, ".//button[text()='Создать аккаунт']"
    LOGIN_AND_REGISTRATION = By.XPATH, ".//button[text()='Вход и регистрация']"
    BUTTON_NO_ACCAUNT = By.XPATH, ".//button[text()='Нет аккаунта']"
    BUTTON_CREATE_CARD = By.XPATH, ".//button[@class='buttonPrimary inButtonText undefined inButtonText']"
    REGISTRANION_FORM = By.XPATH, ".//form[@class='popUp_shell__LuyqR']"
    POPAP_TO_LOGIN = By.XPATH, ".//form[@class='popUp_shell__LuyqR']"
    ERROR_OF_REGISTRATION = By.CLASS_NAME, "input_span__yWPqB"
    CIRCLE_PROFIL = By.CLASS_NAME, "circleSmall"
    POPUP_FOR_AUTORIZATION = By.XPATH, ".//h1[text()='Чтобы разместить объявление, авторизуйтесь']"

    FILD_NAME = By.NAME, "name"
    FILD_DESCRIPTION = By.XPATH, ".//textarea[@class='textarea_inputStandart__IoNxq spanGlobal']"
    FILD_PRICE = By.NAME, "price"
    DROPDAWN_CATEGORY = By.XPATH, "//input[@name='category']/parent::div/button"
    HOBBY_BUTTON = By.XPATH, ".//button/span[text()='Хобби']"
    DROPDAWN_CITY = By.XPATH, "//input[@name='city']/parent::div/button"
    SPB_CITY = By.XPATH, ".//span[text()='Санкт-Петербург']/parent::button"
    RADIOBUTTON_OLD = By.XPATH, "//div[@class='radioUnput_inputRegular__FbVbr']"
    PUBLISH_BUTTON = By.XPATH, "//button[@class='buttonPrimary inButtonText undefined inButtonText']"
    CARD = By.CLASS_NAME, "card"
